# Generated by Django 3.2.12 on 2022-04-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.CharField(max_length=20, unique=True, verbose_name='username'),
        ),
    ]
