# Generated by Django 4.0.3 on 2022-03-19 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserFullName', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('WordID', models.AutoField(primary_key=True, serialize=False)),
                ('InEnglish', models.CharField(max_length=255)),
                ('InNepali', models.CharField(max_length=255)),
                ('InChinese', models.CharField(max_length=255)),
                ('InPinYin', models.CharField(max_length=255)),
                ('InDevnagari', models.CharField(max_length=255)),
                ('Audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
            options={
                'db_table': 'vocabulary',
            },
        ),
    ]
