# Generated by Django 3.2.12 on 2022-04-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0002_rename_word_favourite_vocabulary'),
        ('api', '0003_wordoftheday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WordOfTheDay',
        ),
    ]
