# Generated by Django 3.2.12 on 2022-04-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='word',
            new_name='vocabulary',
        ),
    ]
